# Generated by Django 4.2.13 on 2024-06-01 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_email_alter_user_name_alter_user_password_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='m1',
        ),
    ]
