# Generated by Django 4.2.13 on 2024-06-02 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_user_m1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='m1',
        ),
    ]
