# Generated by Django 4.2.13 on 2024-06-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0005_delete_m1'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=50)),
                ('password', models.TextField()),
                ('Email', models.EmailField(blank=True, default='', max_length=50)),
                ('identity', models.CharField(default='Y', max_length=2)),
            ],
        ),
    ]
