# Generated by Django 4.2.13 on 2024-06-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_userdata_email_alter_userdata_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='Phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
