# Generated by Django 4.2.13 on 2024-06-03 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_userdata_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='identity',
            new_name='Identity',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='password',
            new_name='Password',
        ),
    ]
