# Generated by Django 4.2.13 on 2024-06-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_userdata_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='Phone',
            field=models.CharField(max_length=50),
        ),
    ]
